server:
  port: 3000
  base-url: /gestik
  bin-win: # renombrar a bin para activar esta configuración durante el desarrollo
    zip: c:\Program Files\7-Zip\7z.exe # 7zip debe estar instalado o hay que modificar la configuración zip*:
    zip-fixed-parameters: [a]
    zip-password-parameter-flag: false
    zip-password-prefix: -p
  bin-linux:
    zip: zip  # instalar zip con sudo apt-get intall zip
    zip-fixed-parameters:
      - --junk-paths  # para que no ponga la ruta dentro del zip
db:
  description: base de prueba
  host: localhost
  port: 5432
  database: gestik_db
  schema: gestik
  user: gestik_admin
  password: cambiar_esta_clave
  downloadable-backup-path: c:\temp\backup.sql # lugar donde un cron deja el backup periodicamente (no es reponsabilidad de bp)
install:
  dump:
    db:
      owner: gestik_owner
client-setup: 
  lang: es
devel:
  delay: 0
log:
  db:
    on-demand: true